name: report
repository: github.com/miao2sec/trivy-plugin-report
version: "0.3.3"
maintainer: miao2sec
output: true
summary: A trivy plugin that can convert scan results into excel
usage: Template
description: |-
  A trivy plugin that can convert scan results into excel and markdown
platforms:
  - selector:
      os: linux
      arch: amd64
    uri: ./report
    bin: ./report
